# DataSet Project

In [1]:
import pandas as pd
df = pd.read_csv('Exchange Rates from 1975-2022.csv')
df

,Table 340-46001 : Exchange Rates,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,,Australian Dollar,Canadian Dollar,Chinese Renminbi,Euro (1),Indian Rupee,Indonesian Rupiah,Japanese Yen,Korean Won,Malaysian Ringgit,New Taiwan Dollar,Philippine Peso,Pound Sterling,Singapore Dollar,South African Rand,Swiss Franc,Thai Baht,US Dollar
2,NaN,NaN,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency,HK dollar per unit of foreign currency
3,Year,Month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1975,NaN,6.47,4.86,2.6657,N.A.,N.A.,N.A.,0.0167,0.0098,N.A.,0.130,N.A.,10.90,2.08,N.A.,1.91,N.A.,4.939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
639,Source:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
640,"Trade Analysis Section,Census and Statistics D...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
641,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
642,"Release Date: 1 June, 2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN